name: build_and_test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.8.18

            - name: update submodule
              run: git submodule update --init --recursive

            - name: install scikit-robot
              run: |
                sudo apt-get install libspatialindex-dev freeglut3-dev libsuitesparse-dev libblas-dev liblapack-dev
                pip install scikit-robot

            - name: Install this package
              run: |
                  sudo apt-get install libeigen3-dev
                  pip install scikit-build
                  pip install -e . -v

            - name: Test
              run: |
                pip install pytest
                python3 -c "from skrobot.models.fetch import Fetch; Fetch()"  # create cache
                pytest python
